# Site settings
title: Nadja Herger
url: "http://nherger.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/blog" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
description: >
  This is Nadja Herger's personal blog.

# Your information
email: hergernadja@gmail.com
author: Nadja Herger
avatar: "https://github.com/nherger/blog/blob/gh-pages/photos/portrait.jpg?raw=true"  #"//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Hi there! I'm Nadja from Switzerland, currently living in Australia.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:hergernadja@gmail.com"
  GitHub: "https://github.com/nherger"
  LinkedIn: "https://www.linkedin.com/in/nadja-herger"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Publications: /publications/
#    Category: /category/
#    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax


